char *_memset(char *s, char b, unsigend int n);
char *_memcpy(char *dest, char *dest, char *src, unsigend int n);
char *_strchr(char *s, char c);
unsigend int _strspn(char *s, char *accept);
char *_strpbrk(char *s, char *accept);
char *_strstr(char *haystack, char *needle);
void print_chessboard(char (*a)[8]);
void print_diagsums(int *a, int size);
int _putchar(char c);
void set_string(char **s, char *to);
